openapi: 3.0.1
info:
  title: Dig Airdrop
  description: 'This is the dfy airdrop tool.  It eats JSON arrays with three strings
    and after verifying the signature on the dig address, '
  version: 1.0.0
servers:
- url: https://airdrop.digchain.org/v2
- url: http://airdrop.digchain.org/v2
paths:
  /digme:
    post:
      summary: Add an address to the dig genesis
      operationId: addAddr
      requestBody:
        description: verified address pair
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digger'
        required: true
      responses:
        200:
          description: OK
          content: {}
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
components: 
    schemas:
      Digger:
        type: object
        properties:
          ethaddr:
            type: string
          digaddr:
            type: string
          signature:
            type: string
          

